//! Device trees no firmware would write, and what the parser must do with them.
//!
//! **Every test here is a regression for a bug that was real.** The other two test files parse the
//! device trees QEMU actually hands us; this one is the inverse, and it exists because the blob is
//! the first thing this kernel reads and the last thing it can validate against anything else. The
//! pointer comes from firmware. There is no second opinion.
//!
//! Both bugs below came out of milestone 42's fuzzing leg (`fuzz/fuzz_targets/dtb_walk`, 2026-08-02),
//! and it is worth recording *how*, because they came out differently:
//!
//!   * The deep-nesting index was found by **reading the code** while writing the fuzz target, and
//!     ten minutes of fuzzing did **not** rediscover it. Seventeen levels of nesting with a matching
//!     name at the bottom is structure a mutational fuzzer will not synthesize from a corpus of real
//!     device trees, which are three deep.
//!   * The `Region::end` overflow was found by **the fuzzer**, in about ten minutes, from a mutated
//!     copy of the committed `qemu-aarch64-virt.dtb`. Nobody had thought to look at it.
//!
//! That is the argument for having both, stated as evidence rather than as a slogan. See
//! notes/fuzzing.md.
//!
//! These run on the host in milliseconds, so the inputs that cost real time to find cost nothing to
//! keep.

use dtb::{Dtb, Error, Region};

/// Enough of a device tree to reach the structure block, built from parts.
///
/// The header is 40 bytes of big-endian u32s, then the memory-reservation block (one all-zero entry
/// terminates it), then the structure block, then the strings block. Hand-assembled rather than
/// generated by `dtc`, because the whole point is to write blobs `dtc` would refuse.
struct Blob {
    strings: Vec<u8>,
    structure: Vec<u8>,
}

impl Blob {
    fn new() -> Blob {
        Blob {
            strings: Vec::new(),
            structure: Vec::new(),
        }
    }

    /// Intern a property name and return its offset in the strings block.
    fn string(&mut self, s: &[u8]) -> u32 {
        let at = self.strings.len() as u32;
        self.strings.extend_from_slice(s);
        self.strings.push(0);
        at
    }

    fn token(&mut self, t: u32) -> &mut Self {
        self.structure.extend_from_slice(&t.to_be_bytes());
        self
    }

    /// `FDT_BEGIN_NODE` plus the node's name, NUL-terminated and padded to four bytes.
    fn begin_node(&mut self, name: &[u8]) -> &mut Self {
        self.token(1);
        self.structure.extend_from_slice(name);
        self.structure.push(0);
        while !self.structure.len().is_multiple_of(4) {
            self.structure.push(0);
        }
        self
    }

    fn end_node(&mut self) -> &mut Self {
        self.token(2)
    }

    /// `FDT_PROP`: a length, a name offset, then the value padded to four bytes.
    fn prop(&mut self, name: &[u8], value: &[u8]) -> &mut Self {
        let name_off = self.string(name);
        self.token(3);
        self.structure
            .extend_from_slice(&(value.len() as u32).to_be_bytes());
        self.structure.extend_from_slice(&name_off.to_be_bytes());
        self.structure.extend_from_slice(value);
        while !self.structure.len().is_multiple_of(4) {
            self.structure.push(0);
        }
        self
    }

    fn finish(&mut self) -> Vec<u8> {
        self.token(9); // FDT_END

        const HEADER: usize = 40;
        let off_rsvmap = HEADER;
        let off_struct = off_rsvmap + 16; // one all-zero reservation entry terminates the list
        let off_strings = off_struct + self.structure.len();
        let total = off_strings + self.strings.len();

        let mut b = Vec::with_capacity(total);
        for word in [
            0xd00d_feed,
            total as u32,
            off_struct as u32,
            off_strings as u32,
            off_rsvmap as u32,
            17, // version
            16, // last_comp_version
            0,  // boot_cpuid_phys
            self.strings.len() as u32,
            self.structure.len() as u32,
        ] {
            b.extend_from_slice(&word.to_be_bytes());
        }
        b.extend_from_slice(&[0u8; 16]);
        b.extend_from_slice(&self.structure);
        b.extend_from_slice(&self.strings);
        b
    }
}

/// Two big-endian 64-bit cells: the `#address-cells = 2, #size-cells = 2` layout every 64-bit board
/// uses, which is what the fixtures carry and what `decode_reg` sees in practice.
fn reg64(start: u64, size: u64) -> Vec<u8> {
    let mut v = Vec::new();
    v.extend_from_slice(&start.to_be_bytes());
    v.extend_from_slice(&size.to_be_bytes());
    v
}

/// A tree `depth` levels deep whose deepest node is the only one matching `intc`, and which carries
/// a `reg` there. Depth 1 is the root, so `depth = 17` puts the interesting node at 17.
fn nested(depth: usize) -> Vec<u8> {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    for _ in 0..depth - 2 {
        b.begin_node(b"bus");
    }
    b.begin_node(b"intc@8000000");
    b.prop(b"reg", &reg64(0x800_0000, 0x1_0000));
    for _ in 0..depth {
        b.end_node();
    }
    b.finish()
}

/// **A node nested past the cell stack must not be indexed for.**
///
/// `node_reg` carries `#address-cells`/`#size-cells` down a 16-entry per-depth array, and used to
/// match a node at *any* depth >= 2. At depth 17 the `reg` arm read `acells[depth - 1]`, which is
/// `acells[16]` on a 16-element array: an out-of-bounds index, i.e. a panic, in the parser the
/// kernel runs against a blob it did not write, before there is any way to report a failure.
///
/// The fix refuses to match past the stack rather than clamping the index, so the answer is "no such
/// node" (`Ok(0)`) instead of a region decoded with cell widths this walk stopped tracking.
#[test]
fn a_node_deeper_than_the_cell_stack_is_not_found_rather_than_indexed() {
    let mut out = [Region { start: 0, size: 0 }; 4];

    // Inside the stack: found, and decoded with the root's 2/2 cells.
    let shallow = nested(3);
    let dtb = Dtb::from_bytes(&shallow).unwrap();
    assert_eq!(dtb.node_reg(b"intc", &mut out).unwrap(), 1);
    assert_eq!(
        out[0],
        Region {
            start: 0x800_0000,
            size: 0x1_0000
        }
    );

    // Past it: not found. The assertion that matters is that this returns at all.
    for depth in [16, 17, 24, 40] {
        let deep = nested(depth);
        let dtb = Dtb::from_bytes(&deep).unwrap();
        assert_eq!(
            dtb.node_reg(b"intc", &mut out).unwrap(),
            0,
            "a node at depth {depth} should be reported as absent, not indexed for"
        );
        // The sibling lookups walk the same tree with the same per-depth arrays.
        assert!(dtb.node_reg_compatible(b"arm,pl031", &mut out).is_ok());
        assert!(dtb.node_prop(b"intc", b"reg").is_ok());
    }
}

/// **A `reg` pair whose `start + size` wraps is refused, not passed out.**
///
/// Found by the fuzzer. `Region::end()` was a plain `start + size` on two numbers straight out of the
/// blob, and `kernel/src/memory.rs`'s `place_bitmap` calls it on every RAM region the device tree
/// declares. Under the dev profile's overflow checks (which the kernel's own test builds use) that is
/// a panic on the boot path.
#[test]
fn a_memory_region_that_wraps_the_address_space_is_refused() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    b.begin_node(b"memory@0");
    b.prop(b"reg", &reg64(u64::MAX, u64::MAX));
    b.end_node();
    b.end_node();
    let blob = b.finish();

    let dtb = Dtb::from_bytes(&blob).unwrap();
    let mut out = [Region { start: 0, size: 0 }; 4];
    assert_eq!(
        dtb.memory_regions(&mut out),
        Err(Error::RegionOverflow),
        "a region past the top of the address space is not a region"
    );
}

/// **`Region::end` holds on its own**, whatever built the region.
///
/// The type is `pub` with `pub` fields, so the refusal above is not the only thing standing between
/// a hostile pair and the addition. Saturating is the backstop; the refusal is the check.
#[test]
fn region_end_saturates_rather_than_wrapping() {
    assert_eq!(
        Region {
            start: u64::MAX,
            size: 1
        }
        .end(),
        u64::MAX
    );
    assert_eq!(
        Region {
            start: u64::MAX,
            size: u64::MAX
        }
        .end(),
        u64::MAX
    );
    // The ordinary case is unchanged.
    assert_eq!(
        Region {
            start: 0x4000_0000,
            size: 0x800_0000
        }
        .end(),
        0x4800_0000
    );
}
